### ISSUE TITLE
Hello , 你的pages看起来特别好看，我可以用一下你的模版吗

### ISSUE THREAD

**Issue by EeyoreLee** [ifwind/ifwind.github.io#1]
关于blog内容，我会清理干净，只使用模版。

**Comment by ifwind** [comment]
> 关于blog内容，我会清理干净，只使用模版。

可以的，我用的是butterfly这个主题https://butterfly.js.org/

**Comment by EeyoreLee** [comment]
> > 关于blog内容，我会清理干净，只使用模版。
> 
> 可以的，我用的是butterfly这个主题https://butterfly.js.org/

感谢
